POST http://localhost:8080/auth/login/
Content-Type: application/json
Authorization: Basic root:2019


###

POST http://localhost:8080/auth/refresh-token/
Content-Type: application/json

{
    "token": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJ1c2VySWQiOiIxIiwiZnVsbE5hbWUiOiIuLi4iLCJpYXQiOjE2MTA5NTg3ODN9.EKpWvT8KmM1ffvLSHGj85w3BATlZVnhk2sKyhMgpm5pW5HKZ1K4LmqASh04KEWSXcAVRQeh1DO5E4fR5Sg4weuEfBWLQxOmhIHcgt-AysCRzTr8Pu6i2o_o9WwFAyIRF2fC28GxIzvbF4BY712If-HVTUbaQFPZDIrXPf-J4cWSmXwXxJfwiSJkFfA8fTSHoeofspfDJAHLztElJWrnsXus00-jGNf7K-wGk59zPb_974RI3wPvKzlz42ny6eSyAchhzUDaRKiAQMtrp3_PqDhuOETXSDMahyf-F6VMHienJr3VKEcaDVJ5K3fy5kC-W7HYyp5-XgPvPFcVcum3FcA"
}

###

DELETE http://localhost:8080/auth/logout/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJGdWxsTmFtZSI6Ii8vVE9ETyIsIlVzZXJJZCI6IjI0NjA3NzExMzY3NzQ4Njc3NTgiLCJVc2VyTmFtZSI6InJvb3QiLCJleHAiOjE2MDc1ODY1OTd9.EmYw9gjIF7kk8ZTz3qUJb6Hj5LiInK013ck3fwfopICz5veZvQpr_ovbitFi62uimveCz9ev1ADHDEIjAfPBgSU-TeNNoGK8ax0SnP389FvrBsg5Hm7NscopwRKlJrWXDdP_FHdixey4cDwkjUT7IO0OFo9L7KpgWgNPtTcUpq0

###


PUT http://localhost:8080/auth/change-pw/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJGdWxsTmFtZSI6Ii8vVE9ETyIsIlVzZXJJZCI6IjEiLCJVc2VyTmFtZSI6InJvb3QiLCJleHAiOjE2MTY1OTE1OTJ9.kE1NaySDVKAFAhwuKmcJSXCns5PXwfV2icFG7iQaBw37sjGouGY0R0LaEOmgYD_RhGVW_A69rTJwgddFgqhGrHyfY1nM7AzJ7BdKzpMeiW0lwRovdQOKFelRJucLXCnu3uhvMSdc2VOUhAv1BzB1GQEz32b2N7RQ0pWN68q2zPc

{
    "currentPassword": "2019",
    "newPassword": "2020"
}